SLASH_REVIVEMACRO1 = "/absurdrevive"
name=
{
    "Shrek",
    "Big Chungus",
    "Nicolas Cage",
    "Bob Ross",
    "Danny DeVito",
    "The Spirit of Disco",
    "Gordon Ramsay's Left Eyebrow",
    "Kanye West",
    "GigaChad",
    "Your Mom",
    "Ancient Aliens Guy",
    "The Entire Cast of Friends",
    "The Ghost of Steve Jobs",
    "A Slightly Moist Sock",
    "Putin Riding a Bear",
    "Patrick Bateman on Creatine",
    "Anime Jesus",
    "Walter White in Tighty Whities",
    "The IKEA Meatball God",
    "That Guy Who Always Rolls Need on Cloth",
    "A Sentient T-Pose",
    "Keanu Reeves in a bathrobe",
    "Eldritch Bob Barker",
    "The Void That Judges Us All",
    "The Last Slice of Pizza",
    "Elon Musk's Twitter Feed",
    "Chuck Norris’ Unused Roundhouse Kick",
    "Your Search History",
    "Spongebob on Preworkout",
    "The Bored Intern Running This Server",
    "Garfield With Existential Dread",
    "Joe Stalintense",
    "Kim Illest Un",
    "Vlad the Slightly Too Impaler",
    "NapoleOwn’d Bonerpart",
    "Adolf Quitler",
    "Benito Swagolini",
    "Ivan the Mediumly Irritated",
    "Pol Potluck",
    "Chairman *Ow*",
    "Mao ZeSwag",
    "Saddam Insane-o",
    "Bashar al-Spaghetti",
    "Francisco FanFranco",
    "Heinrich Hissler",
    "King Jong-Fun",
    "Osama bin Vibin’",
    "Julius Seizure",
    "Attila the Bum",
    "Nero Fiddlesticks",
    "Ceau?eSucku",
    "Mussolame",
    "Idi Oopsie",
    "Maximilian Robospierre",
    "Jeffrey Epclown",
    "Raspootin’",
    "Genghis *Kanned*",
    "Caligoolio",
    "King Henry the Whoreth",
    "Charles D'ickhead III",
    "Kim-Jump-On",
    "Wladimir Plutonium",
    "George W. Push",
    "Lord Cringemort",
    "Jar Jar Stinks",
    "Captain Flatulence",
    "Budget Gandalf",
    "Yoda’s Evil Twin",
    "Brodo Swaggins",
    "Chad the Betrayer",
    "Peter Griffin's Left Foot",
    "Rick Rolled Himself",
    "Subwoofer the Goblin",
    "Your Uncle at BBQ",
    "Darth Vape",
    "Frodo’s Therapist",
    "Chewbarka",
    "Karen the Unyielding",
    "Elmo the Unforgiven",
    "Barney the Bloodthirsty",
    "Thanos but Lacking Sleep",
    "Shampoo Orcslayer",
    "Morbin’ Jared",
    "Elrond’s Tax Accountant",
    "Santa Claws",
    "Professor Painbow",
    "Dark Lord Spaghetti",
    "Mario’s Shadow Clone",
    "Donkey Kong’s Financial Advisor",
    "Post Malone Clone #3",
    "The Boomkin of Regret",
    "Edgelord Supreme",
    "Snape On Ice",
    "Bruce Wane't",
    "Beavis the Beheaded",
    "Crusty Sock Sorcerer",
    "NPC Named Error_404",
    "Socially Awkward Lich",
    "Muffin the Merciless",
    "The Forgotten Minion",
    "Cursed Minimap Ping",
    "Eternal Lag Beast"
};
mes1=
{
  "Get up",
  "Rise and shine",
  "Wake up already",
  "Time to stop dying",
  "Respawn faster",
  "Stand up straight",
  "This isn’t nap time",
  "Back on your feet",
  "Return to the living",
  "Quit slacking",
  "Shake it off",
  "Resurrect, fool",
  "It’s not your bedtime",
  "Don’t make me come down there",
  "Up you go",
  "Walk it off",
  "Live, damn it",
  "Snap out of it",
  "Stop playing dead",
  "This is not a vacation",
  "You can’t die here",
  "Get your corpse moving",
  "On your feet, champion",
  "Get your pixels together",
  "You’re not done yet",
  "You fainted like a Sim",
  "No dying on my watch",
  "Don’t you dare release",
  "Time to tank again",
  "You’ve got work to do",
  "Time to pretend you're useful again",
  "Shake off that dirt nap",
  "You call that a death?",
  "Respawn protocol initiated",
  "I just buffed you, seriously?",
  "You owe me 5 gold for this",
  "This is getting embarrassing",
  "Even Hogger lasted longer",
  "You had one job",
  "Live harder",
  "Channel your inner noob",
  "Corpse time’s over",
  "Don’t go toward the light",
  "I believed in you... kinda",
  "This is why we can’t have nice things",
  "Don’t embarrass the guild",
  "Try not dying next time",
  "Your bed’s not this comfy",
  "Res timer ain't your alarm clock",
  "You disappoint the ancestors",
  "I was eating and you died?!",
  "Hit accept before I change my mind",
  "I should leave you here",
  "Time to simulate skill",
  "This isn't a museum of failures",
  "Graveyards are for quitters",
  "Don’t waste my mana again",
  "I swear this is your last rez",
  "That fall didn’t look that high",
  "Your death was very on-brand",
  "I’m keeping your loot",
  "Rez tax applied",
  "Move it, weakling",
  "Time to prove you’re more than a number",
  "You’re the raid’s mascot now",
  "I’ll raise you, but not your IQ",
  "This is not a spa treatment",
  "Stop cosplaying a skeleton",
  "Get up, emo lord",
  "Your DPS died with you",
  "I don’t resurrect cowards, just you",
  "Even Leeroy did better",
  "I’ll rez you just to watch you die again",
  "You've been benched by gravity",
  "Back to work, peasant",
  "F in chat",
  "Don’t release — I’m not done mocking you",
  "This is your sign to stop sucking",
  "This is a pitiful pattern",
  "Let’s try not being dead this time",
  "Please return to your assigned corpse",
  "This is a guilt rez",
  "That ghost form looks good on you",
  "I expect memes about this",
  "Even the boss looked away",
  "Arise, fallen meme",
  "Back from irrelevance",
  "Back into mediocrity you go",
  "Time to get carried again",
  "I’m not paid enough for this",
  "You're making Spirit Healers rich",
  "You lost the duel with a flower",
  "I’m rezzing you ironically",
  "The repair bill is not my fault",
  "Do you even keybind?",
  "Stop RP walking through life",
  "Back from the cringerealm",
  "Now with more failure resistance",
  "Another chapter in your saga of shame",
  "Congratulations, you played yourself",
  "You are the weakest link",
  "Insert coin to continue",
  "Your training arc continues",
  "Up and die again"
}
mes2=
{
  "is not impressed.",
  "is watching you closely.",
  "demands your presence.",
  "doesn’t accept failure.",
  "was counting on you.",
  "already looted your body.",
  "refuses to carry you.",
  "saw that and cringed.",
  "is disappointed beyond words.",
  "called you weak in Discord.",
  "used your death as content.",
  "clipped that for TikTok.",
  "won’t heal you next time.",
  "just shook their head slowly.",
  "screamed in 14 dimensions.",
  "whispered 'pathetic' into the void.",
  "summoned you back through shame.",
  "offered no sympathy.",
  "blames your keyboard.",
  "just deleted your name from the will.",
  "posted about you on the forums.",
  "cried a single tear.",
  "reported you to the Raid Council.",
  "felt a disturbance in the cringe.",
  "updated your status to 'deadweight'.",
  "unfriended you spiritually.",
  "rated your death 2/10.",
  "drew fanart of you dying.",
  "laughed so hard they wiped.",
  "thinks you're slacking on purpose.",
  "sent your soul back postage due.",
  "used your last breath as a meme tag.",
  "photoshopped your tombstone.",
  "critiqued your form mid-death.",
  "just ghosted your spirit.",
  "tweeted your failure to Elune.",
  "plagiarized your combat log.",
  "knows this was your peak.",
  "turned your death into a YouTube short.",
  "used your body as a loot table.",
  "mistook you for a dungeon prop.",
  "rejected your soul at the gate.",
  "filed your death under 'meh'.",
  "called the janitor for your corpse.",
  "put you on a guild blacklist.",
  "autographed your gravestone.",
  "just leveled up from watching you die.",
  "banned you in ghost chat.",
  "commented 'skill issue'.",
  "rated your faceplant a 3/10.",
  "subscribed to your downfall.",
  "got PTSD from your rotation.",
  "left a Yelp review on your death.",
  "hit ctrl+z on your existence.",
  "reported your death as a bug.",
  "gave your gear to the vendor.",
  "mistook you for a training dummy.",
  "used your body to skip a mechanic.",
  "felt your death in the economy.",
  "linked your DPS as a warning.",
  "despawned from secondhand shame.",
  "filtered you out of their memories.",
  "used your death to pad meters.",
  "saved over your character slot.",
  "revoked your license to raid.",
  "emailed your spirit.",
  "named a disease after you.",
  "rescheduled your funeral again.",
  "laughed in binary.",
  "got secondhand embarrassment.",
  "sent your corpse on a side quest.",
  "updated the guild death leaderboard.",
  "tied your spirit to a rock.",
  "recycled your soul into a mob.",
  "mained your shame.",
  "DM’d Death itself for feedback.",
  "thanked you for the wipe.",
  "logged off in protest.",
  "cosplayed your failure.",
  "got bored and summoned a ghoul.",
  "teleported your ghost to Thunder Bluff.",
  "just used your face as a keyboard.",
  "nominated you for 'Most Dead'.",
  "told their mom about your death.",
  "spammed /sit at your corpse.",
  "honored you with a fart emote.",
  "paid gold to see you fail.",
  "clipped your death for a soundboard.",
  "got karma from watching.",
  "trolled your spirit with whispers.",
  "said 'oops' with a smirk.",
  "offered you to the boss gods.",
  "used your name as a safe word.",
  "sent your logs to Blizzard.",
  "marked your death on the calendar.",
  "made a haiku about it.",
  "left your ghost on read.",
  "equipped your shame as transmog.",
  "pushed you into the afterlife queue.",
  "muted your soul.",
  "dealt emotional crit damage.",
  "blamed your mousepad."
};

local function tableLength(t) -- the # doesn't work, so a function to count a table's length is required
  local count = 0
  for _ in pairs(t) do
    count = count + 1
  end
  return count
end

local _, class = UnitClass("player")
local rezSpell;
if class=="SHAMAN" then rezSpell="Ancestral Spirit";
elseif class=="PRIEST" then rezSpell="Resurrection";
elseif class=="PALADIN" then rezSpell="Redemption";
elseif class=="DRUID" then rezSpell="Rebirth";
end

SlashCmdList["REVIVEMACRO"] = function()
    local r_name=random(tableLength(name));
    local r_mes1=random(tableLength(mes1));
    local r_mes2=random(tableLength(mes2));
    if
    UnitIsDead("target")
    then CastSpellByName(rezSpell) c="say" SendChatMessage(mes1[r_mes1].." %t! "..name[r_name].." "..mes2[r_mes2], c, nil, UnitName("player"));
    end
end
