--dont use ’, because WoW interface doesn't show it, use ' instead.

SLASH_REVIVEMACRO1 = "/absurdrevive" --it's obviously used to assign a command for the addon

mes1={}; --tables (lists) with the subsets (types) of messages
mes2={};

local function tableLength(t) -- the # doesn't work, so a function to count a table's length is required
  local count = 0
  for _ in pairs(t) do
    count = count + 1
  end
  return count
end

mes1[1]= --just funny ones
{
    "Rise and shine, ",
    "Time to stop napping, ",
    "Back to life with you, ",
    "Get up, hero, ",
    "Un-die now, ",
    "Stand tall again, ",
    "The gods demand your return, ",
    "Time to shine, champion, ",
    "Awaken! ",
    "On your feet again, ",
    "Return from the nether, ",
    "Come back, ghostling, ",
    "Wake up, sleepyhead, ",
    "The raid needs your sarcasm, ",
    "No more floor tanking, ",
    "Get your pixels upright, ",
    "Resisting dirt is futile, ",
    "We missed your yelling, ",
    "You're too beautiful to stay dead, ",
    "We ran out of excuses without you, ",
    "Get up before the loot disappears, ",
    "The floor's not a mount, ",
    "Your repair bill can wait, ",
    "You owe me a potion for this, ",
    "Death doesn't suit you, ",
    "You're late for being alive, ",
    "They noticed you weren't screaming, ",
    "This isn't nap club, ",
    "They're still blaming you, ",
    "Return! For science, ",
    "I told death to take a coffee break, ",
    "Your corpse is underperforming, ",
    "Time to die again, but slower, ",
    "We need a target for the next cleave, ",
    "Your DPS can't possibly get worse, ",
    "I need someone to stand in fire, ",
    "The mobs miss you, ",
    "You left your alt-tab open, ",
    "The floor wrote a poem about you, ",
    "The boss stopped laughing, ",
    "They're rolling need without you, ",
    "It's not a wipe without your dance, ",
    "Your bones are hurting my eyes, ",
    "You're holding up the comedy, ",
    "Don't let death interrupt your trolling, ",
    "I cast life on thee, ",
    "You owe me gold for this, ",
    "Rise, loot sponge, ",
    "Rebooting consciousness, please wait... ",
    "Ctrl+Z-ing your existence, ",
    "Bringing back the weak sauce, "
};
mes2[1]=
{
   ", the floor isn't that comfy.",
    ", the boss misses your screams.",
    ", we still need a scapegoat.",
    ", your 0 DPS won't cast itself.",
    ", and pretend this never happened.",
    ", and go wipe us properly this time.",
    ", to press the wrong button once more.",
    ", or at least glow faintly.",
    ", the enemies aren't done laughing.",
    ", so you can die better next time.",
    ", because I need someone to blame.",
    ", before the next pull goes wrong.",
    ", to remind us why we don't pug.",
    ", and save us with your silence.",
    ", because the healers are bored.",
    ", you forgot to die with style.",
    ", the mobs were disappointed.",
    ", our damage meters feel empty.",
    ", so we can question your spec again.",
    ", because death is overrated.",
    ", you left your corpse unlocked.",
    ", before someone else ninja-loots.",
    ", because the raid needs comedy relief.",
    ", and show us how not to stand.",
    ", the tank needs emotional support.",
    ", and earn your wipe count badge.",
    ", the guild morale depends on your pain.",
    ", because you look hilarious when rezzing.",
    ", to show us where *not* to stand.",
    ", our tactics need your confusion.",
    ", and take this second chance to fail.",
    ", and teach the floor who's boss.",
    ", the raid lead ran out of insults.",
    ", your death made the imp cry.",
    ", and tell death we're not done.",
    ", and continue underperforming.",
    ", and explain why you're naked.",
    ", because I clicked the wrong spell.",
    ", so you can fail with dignity.",
    ", and update your death counter.",
    ", to relive that last mistake.",
    ", and use your healthstone properly this time.",
    ", because the fire feels lonely.",
    ", to revive morale (not just you).",
    ", and keep standing awkwardly.",
    ", so we can yell at you again.",
    ", and rejoin us in glorious mediocrity.",
    ", to keep the failure evenly distributed.",
    ", and impress the repair vendor."
}
mes1[2]= --horror style
{
   "From the depths you crawl, ",
    "The shadows release you, ",
    "A whisper calls you back, ",
    "The cold grip loosens, ",
    "Darkness surrenders you, ",
    "A chilling breath revives, ",
    "The grave has let you go, ",
    "The silence breaks, ",
    "A flicker in the abyss, ",
    "The void relinquishes its hold, ",
    "Death's cold hand falters, ",
    "Emerge from the nightmare, ",
    "The darkness weeps as you rise, ",
    "A cursed spark reignites, ",
    "The night yields your soul, ",
    "Phantoms retreat before you, ",
    "The veil thins for your return, ",
    "The dead speak your name, ",
    "A shadow fades away, ",
    "Your fate is rewritten, ",
    "Cold hands pull you back, ",
    "The lost find their way, ",
    "A breath escapes the void, ",
    "Silent screams echo near, ",
    "The darkness calls your name, ",
    "The tomb cracks open, ",
    "Shadows dance with your soul,",
    "The night stirs again, ",
    "Your heartbeat breaks the silence, ",
    "Echoes of death fade, ",
    "The curse unwinds its grip, ",
    "A phantom's tear revives you, ",
    "The abyss stares and blinks, ",
    "The grave sighs, releasing you, ",
    "A ghostly hand drags you forth, ",
    "The eternal night flickers, ",
    "Death's chill fades away, ",
    "The lost soul awakens, ",
    "The darkness shudders, ",
    "Your spirit stirs anew, ",
    "The crypt exhales, ",
    "A flicker returns within, ",
    "Bones crack and reform, ",
    "The cursed clock resets, ",
    "Whispers echo through the tomb, ",
    "Your breath returns, ",
    "The abyss cracks open, ",
    "Shadows recoil as you rise, ",
    "The dead's embrace loosens, ",
    "Cold mist swirls around, ",
    "Fingers of darkness retreat, ",
    "The veil between fades, ",
    "Your pulse returns from silence, ",
    "Graveyard winds howl softly, ",
    "The dark whispers your name, ",
    "Life stirs in the decay, ",
    "Nightmares break their chains, ",
    "The ghostly veil lifts, ",
    "The soul's flame flickers, ",
    "Cold fingers release their grip, ",
    "Echoes of the forgotten return, ",
    "The tombstone trembles, ",
    "Death's shadow shrinks back, ",
    "The cursed night wanes, ",
    "A dark spark ignites anew, ",
    "The void's grip falters, ",
    "Shadows scatter at your step, ",
    "The grave's silence breaks, ",
    "The eternal dusk recedes, ",
    "Phantom chains fall away, "
}
mes2[2]=
{
    ", but the nightmare lingers.",
    ", to suffer once more.",
    ", yet the fear remains.",
    ", and death watches silently.",
    ", condemned to endless torment.",
    ", yet never truly free.",
    ", and the silence screams.",
    ", doomed to walk again.",
    ", but the darkness watches.",
    ", cursed to bleed again.",
    ", yet the horror follows.",
    ", forever haunted by shadows.",
    ", and the cold never leaves.",
    ", but whispers never cease.",
    ", bound to the eternal night.",
    ", while phantoms whisper lies.",
    ", your soul still trembles.",
    ", where shadows dare not tread.",
    ", but the terror never fades.",
    ", and fate waits patiently.",
    ", though the cold grasps tighter.",
    ", as lost voices wail.",
    ", with silence as your shroud.",
    ", beneath the watching eyes.",
    ", the shadows clutch harder.",
    ", and bones crack anew.",
    ", through veils of mist.",
    ", where light dares not enter.",
    ", beneath the blood-red moon.",
    ", and the grave's cold breath.",
    ", till darkness claims you again.",
    ", with a cursed heartbeat.",
    ", where echoes die last.",
    ", beneath the howling wind.",
    ", as the void reaches out.",
    ", and cold whispers call.",
    ", lost within endless night.",
    ", and shadows never sleep.",
    ", until the end of time.",
    ", as the final breath fades.",
    ", but the dread remains.",
    ", forever marked by darkness.",
    ", yet the shadows watch.",
    ", condemned to endless wandering.",
    ", though light is but a memory.",
    ", but your fate is sealed.",
    ", cursed to roam the night.",
    ", but the ghosts linger still.",
    ", though the chill never fades.",
    ", haunted by silent screams.",
    ", beneath the bloodied moonlight.",
    ", with whispers in the dark.",
    ", and the shadows whisper lies.",
    ", cursed to never rest.",
    ", as the night devours hope.",
    ", lost to time's cruel hand.",
    ", where shadows hunger still.",
    ", forever lost to the void.",
    ", beneath the weeping skies.",
    ", with a hollow heartbeat.",
    ", yet the darkness waits.",
    ", as your soul slowly fades.",
    ", chained to endless sorrow.",
    ", where nightmares never end.",
    ", shrouded in eternal dusk.",
    ", with silence as your guide.",
    ", bound to the cursed earth.",
    ", as the cold winds moan.",
    ", forever trapped in twilight.",
    ", until the stars burn out."
}
mes1[3]= --goldman sachs style
{
    "Subject revival protocol initiated for ",
    "Reactivation process authorized on entity ",
    "Operational continuity reinstated for unit ",
    "Resource recovery in progress: ",
    "Corporeal re-entry sequence launched for ",
    "Standard resurrection compliance executed on ",
    "Emergency asset reallocation targeting ",
    "Stakeholder revival request granted: ",
    "Risk-adjusted soul return protocol engaged for ",
    "Revival metrics met. Proceeding with reanimation of ",
    "Performance recovery engagement initiated on ",
    "Corpse liability neutralized, proceeding with ",
    "Departmental override confirmed: resurrecting ",
    "Value retention protocol triggered for ",
    "Q4 revival initiative greenlit for ",
    "Non-performing unit detected. Recovery initiated on ",
    "Temporal realignment complete, reinstating ",
    "P&L anomaly resolved. Soulflow unlocked for ",
    "Escrow of ethereal essence concluded. Welcome back, ",
    "Revival request escalated and approved for ",
    "Back-office approval complete. Rebooting ",
    "Soul assets restructured. Deploying revival to ",
    "Crisis management procedure active on ",
    "Allocated mana reserves sufficient. Targeting ",
    "Post-failure reconciliation active. Restoring ",
    "Injury report finalized. Resurrecting ",
    "Interdepartmental consensus reached. Raising ",
    "Survivability index recalibrated. Executing revive on ",
    "Revive quota fulfillment in progress. Now reviving ",
    "KPI-adjusted resurrection activated for "
}
mes2[3]=
{
    ". Please remain within performance benchmarks.",
    ". Kindly avoid further downtime incidents.",
    ". Your death has been logged and reviewed.",
    ". Further failure may impact bonus eligibility.",
    ". Consider revising your engagement strategy.",
    ". Future revival may require team approval.",
    ". Resume operations with minimal disruption.",
    ". Your respawn has been risk-audited.",
    ". Soul reintegration complete. Monitor volatility.",
    ". Compliance expects increased situational awareness.",
    ". Post-mortem report submitted.",
    ". Mistake has been internally escalated.",
    ". Target performance recalibration recommended.",
    ". Further inefficiencies will trigger alerts.",
    ". This was your complimentary revive.",
    ". You now operate under closer supervision.",
    ". Return to productivity immediately.",
    ". Please confirm receipt of resurrection.",
    ". A ticket has been opened on your death.",
    ". Consider this a strategic realignment.",
    ". Please refrain from repeating this behavior.",
    ". Our patience is not infinite.",
    ". Reinstatement under provisional terms.",
    ". Audit trail restored. Get moving.",
    ". Next failure may result in restructuring.",
    ". Your metrics are being monitored.",
    ". Welcome back. Please try not to explode.",
    ". We've forwarded this incident to HR.",
    ". Death insurance premiums may rise.",
    ". Don't expect this treatment twice."
}
mes1[4] = --exaggerated english speaking style
{
  "Oh dear heavens, we appear to have misplaced ",
  "By Jove! Someone revive the noble spirit of ",
  "Gracious me, not again! Someone fetch ",
  "Egads! The gallant soul of ",
  "Goodness gracious, another casualty! It's ",
  "I daresay, Death has been rather unkind to ",
  "The battlefield laments the absence of ",
  "Summon the tea and biscuits, we've lost ",
  "By the Queen's corgis! It's poor ",
  "Sound the trumpets! We're restoring ",
  "A tragedy of Shakespearean proportions befallen ",
  "Arise, brave champion, namely ",
  "Another bite o' the scone, welcome back ",
  "Oh bother, I suppose we need ",
  "Not on my watch, Death! Return ",
  "A toast! To the return of ",
  "Well butter my crumpet, it's ",
  "Heavens above! Someone scooped up ",
  "Do lift thyself, noble soul, ",
  "Oh what rot! Back to life with thee, ",
  "Sir/Madam, your nap hath ended — rise, ",
  "Dash it all! Wake up, ",
  "Even Death blushed at the sight of ",
  "M'lady Death, kindly return ",
  "This is no time for dying, dear ",
  "The spirit world sent back ",
  "One simply *does not* stay dead, ",
  "Cheerio! Back on your feet, ",
  "The tea's gone cold without ",
  "Back from the beyond, it's ",
}
mes2[4] =
{
  ", and do mind the bloodstains next time.",
  ", now chin up and carry on, won't you?",
  ", and do refrain from such dramatics henceforth.",
  ", because Death said you were far too whiny.",
  ", now make haste and pretend you're helpful.",
  ", and not a word about this to the Queen.",
  ", and try not to keel over mid-fight again.",
  ", tea is at four, don't be late again.",
  ", and kindly avoid reenacting Hamlet.",
  ", the afterlife was full anyway.",
  ", and the undead say they don't want you either.",
  ", now remember: pinky up when casting.",
  ", and for goodness' sake, dodge!",
  ", and I say, the grave did *not* suit you.",
  ", now act like you've some breeding.",
  ", and that's quite enough fainting for today.",
  ", but do mind where you place your corpse next time.",
  ", and this time, scream with dignity.",
  ", and do try looking *less* dead.",
  ", and by all means, flop more gracefully next time.",
  ", and you've missed elevenses.",
  ", but your performance was simply ghastly.",
  ", and the tea's gone cold waiting for you.",
  ", and Death sends her regards.",
  ", and the Queen is *not* amused.",
  ", and tell the Reaper he owes me a pint.",
  ", and don't let the lich hit you on the way out.",
  ", and yes, everyone *did* see that.",
  ", and next time, die with *some* flair.",
  ", and fetch me my smelling salts.",
}
mes1[5]= --laughing at stereotypes
{
  "Rise and shine, ",
  "Get up, caffeine fiend, ",
  "Back from your third coffee break, ",
  "Hey there, tech bro, ",
  "Wake up, Midwest casserole champion, ",
  "Up and at 'em, Florida man, ",
  "Dust off that yoga mat, ",
  "Come on, avocado toast enthusiast, ",
  "Snap out of your hipster haze, ",
  "Time to stop pretending you love kale, ",
  "Quit scrolling, social media addict, ",
  "No more binge-watching, Netflix pro, ",
  "Get off your kombucha throne, ",
  "The BBQ king must rise, ",
  "Coffee's brewing for you, city slicker, ",
  "Put down the energy drink, gamer, ",
  "Break time's over, meme lord, ",
  "Awaken, gym rat, ",
  "Quit flexing your phone, influencer, ",
  "Stop napping like a sleepy librarian, ",
  "Time to show that tie who's boss, corporate drone, ",
  "Up you go, dad joke specialist, ",
  "Shake off that Midwest politeness, ",
  "Get out of the man cave, nerd, ",
  "The craft beer connoisseur must join us, ",
  "Put down the vape, rebellious teen, ",
  "Hey, Netflix documentary fanatic, ",
  "Back from your online shopping spree, ",
  "Rise, social justice warrior, ",
  "Stop ghosting and respawn already, "
}
mes2[5]=
{
  ", the Wi-Fi's still slow.",
  ", your kombucha's gone flat.",
  ", your quinoa is soggy.",
  ", your Tesla ran out of charge.",
  ", your casserole is burning.",
  ", the alligator's still waiting.",
  ", your yoga pants need washing.",
  ", your beard is uneven again.",
  ", the vinyl won't spin itself.",
  ", kale can't save you now.",
  ", your phone battery's at 1%.",
  ", your popcorn's gone stale.",
  ", your kombucha's lost its fizz.",
  ", the grill's cold and lonely.",
  ", your latte art is mediocre.",
  ", your headset's unplugged.",
  ", your meme stash is outdated.",
  ", your protein shake spilled.",
  ", your selfies need retaking.",
  ", your books are still unread.",
  ", your tie is crooked again.",
  ", your punchline fell flat.",
  ", your Midwestern charm can't save you.",
  ", your comic books miss you.",
  ", your IPA is warm.",
  ", your vape trick failed again.",
  ", your subscription expired.",
  ", your delivery is delayed.",
  ", your Twitter feed's on fire.",
  ", your ghosting skills aren't working."
}
mes1[6] = --naruto style
{
    "Believe it! Get up, ",
    "Shadow clone, revive ",
    "Chakra's calling you, ",
    "Time to awaken, ",
    "Summoning jutsu for ",
    "Hokage demands your rise, ",
    "By the power of the Nine-Tails, ",
    "Ninja way never ends, ",
    "Sasuke's waiting for ",
    "Rasengan incoming for ",
    "You're not a genin yet, ",
    "Tailed beast mode: activate ",
    "The leaf village needs you, ",
    "Sharingan says wake up, ",
    "Sakura's healing touch awaits ",
    "It's no jutsu, it's revival, ",
    "Naruto believes in you, ",
    "Get ready for the next mission, ",
    "Rinnegan watching, rise ",
    "Kunai in hand, ",
    "The path of a shinobi calls ",
    "Shadow moves for ",
    "Summon the toad, ",
    "Senju spirit revives ",
    "By the will of fire, ",
    "The battle's not over for ",
    "Chidori charges up for ",
    "You can't run from destiny, ",
    "The Akatsuki missed you, ",
    "It's time to fight again, "
}
mes2[6] =
{
    ", and the village is counting on you.",
    ", don't let your shadow fade.",
    ", the chakra flows strong again.",
    ", and your ninja way shines bright.",
    ", prepare your jutsu once more.",
    ", the Hokage believes in you.",
    ", unleash the power within.",
    ", the shinobi path never ends.",
    ", Sasuke's eyes are upon you.",
    ", Rasengan's ready to spin again.",
    ", no genin stays down forever.",
    ", tailed beast power restored.",
    ", the Leaf Village stands behind you.",
    ", Sharingan sees your return.",
    ", Sakura's got your back again.",
    ", revival is your ultimate jutsu.",
    ", Naruto's spirit lifts you up.",
    ", mission awaits, shinobi.",
    ", Rinnegan guides your soul.",
    ", kunai ready for the next throw.",
    ", the shinobi code lives in you.",
    ", shadow clones gather once more.",
    ", summon the toad and rise.",
    ", Senju strength returns with you.",
    ", by the will of fire, stand tall.",
    ", battle continues, don't back down.",
    ", Chidori strikes anew.",
    ", destiny pulls you back to fight.",
    ", Akatsuki can't stop your rise.",
    ", the fight isn't finished yet."
}
mes1[7] = -- kawai style
{
    "Nyaa~ Wake up, cutie, ",
    "Sparkle time! Get up, ",
    "Your kawaii levels are dropping, ",
    "Bubbles and fluff say rise, ",
    "You can't nap on this kawaii train, ",
    "Glitter's waiting for you, ",
    "Time to shine bright, ",
    "Your sparkle meter needs refilling, ",
    "Cuteness overload incoming, ",
    "Fluffy paws say get up, ",
    "The plushies demand your presence, ",
    "Mew~ Don't snooze, ",
    "You're too adorable to stay down, ",
    "Kawaii vibes require your attendance, ",
    "Time to dance with sparkles, ",
    "Your chibi self is waiting, ",
    "Sweetness alert! Get moving, ",
    "Squee! It's revival time, ",
    "Glitter bombs ready to launch, ",
    "Magical fluff needs you, ",
    "You're the sparkle in our eyes, ",
    "Don't let the cute fade away, ",
    "Rainbow power activates, ",
    "Your fluff-factor is zero, ",
    "Rise, my sparkly friend, ",
    "Cutie patootie, get up, ",
    "Time for snuggles and rezzes, ",
    "Your sparkle aura is fading, ",
    "Bounce back with fluffy energy, ",
    "Glowy cheeks say 'get up'!"
}
mes2[7] =
{
    ", or the kittens will be sad.",
    ", because the stars need your shine.",
    ", and the sparkles will dim forever.",
    ", or the cupcakes will lose their frosting.",
    ", and the bunnies will hop away.",
    ", before the rainbows disappear.",
    ", and the magical ponies will cry.",
    ", or the sparkle fairies will fly off.",
    ", and the fluff clouds will deflate.",
    ", before the cotton candy melts.",
    ", or the cherry blossoms won't bloom.",
    ", and the little plushies will pout.",
    ", before the confetti stops falling.",
    ", or the candy hearts will lose flavor.",
    ", and the unicorns lose their magic.",
    ", before the cupcakes get stale.",
    ", or the twinkle lights go out.",
    ", and the fairy dust blows away.",
    ", before the marshmallows get lonely.",
    ", or the rainbow fades to gray.",
    ", and the sparkly stickers peel off.",
    ", before the bubblegum loses its pop.",
    ", or the candy canes break in half.",
    ", and the pastel skies turn dull.",
    ", before the sparkles lose their bounce.",
    ", or the glitter bombs never explode.",
    ", and the fuzzy slippers go missing.",
    ", before the magical girl cries.",
    ", or the sweet dreams get stolen.",
    ", and the glow sticks flicker out."
}
mes1[8] = -- exaggerated gypsy style
{
    "Oh, rise from the shadows, ",
    "The spirits call you back, ",
    "Hear the drumbeat, ",
    "The cards reveal your fate, ",
    "By the fire's glow, ",
    "The winds whisper your name, ",
    "Dance with the stars, ",
    "The moonlight beckons, ",
    "The fortune's changing, ",
    "Awaken, child of the road, ",
    "The mystic's spell takes hold, ",
    "From the caravan's smoke, ",
    "The night sings your return, ",
    "Magic stirs your soul, ",
    "The crystal ball clears, ",
    "The ancient ones watch, ",
    "The drum calls you home, ",
    "From the caravan's dance, ",
    "The fates twist anew, ",
    "The fire crackles for you, ",
    "The spirits stir, ",
    "Your fortune unfolds, ",
    "The stars align again, ",
    "The wind carries your breath, ",
    "The flame burns brighter, ",
    "The veil parts for you, ",
    "The roads welcome you back, ",
    "The mystic's eye opens, ",
    "The fate wheel spins, ",
    "The dance must go on, "
}
mes2[8] =
{
    ", so the cards say.",
    ", and the drum will guide you.",
    ", for your luck is not done.",
    ", and the stars foretell your path.",
    ", as the night wraps around you.",
    ", and the spirits dance in delight.",
    ", so the fire says to rise.",
    ", and the winds sing your name.",
    ", for destiny awaits your step.",
    ", beneath the glowing moon.",
    ", and the mystic's power grows.",
    ", as the caravan rides on.",
    ", and the fates smile upon you.",
    ", so the crystal shows the way.",
    ", and the ancestors nod in approval.",
    ", with a kiss of magic's breath.",
    ", so your journey continues anew.",
    ", beneath the velvet sky.",
    ", and the drum beats your heart.",
    ", as the night wraps its arms around you.",
    ", so the fortune tells the tale.",
    ", and the stars wink with mischief.",
    ", so your spirit rises again.",
    ", beneath the caravan's moonlight.",
    ", and the roads call your name.",
    ", with the magic of the ages.",
    ", as the veil of fate lifts.",
    ", so the winds whisper secrets.",
    ", beneath the dancing flames.",
    ", and the mystic's song plays on."
}
mes1[9] = -- exaggerated US redneck style
{
    "Well butter my butt and call me a biscuit, ",
    "Git up, y'all hear me, ",
    "Time to quit nappin', ",
    "Ain't no time fer layin' down, ",
    "Rise 'n shine, partner, ",
    "Shake off that hay fever, ",
    "Quit hoggin' the dirt, ",
    "Y'all better get a move on, ",
    "Wake up, cowboy, ",
    "Don't be slackin' now, ",
    "Get back in the saddle, ",
    "The rooster done crowed, ",
    "Ain't no dead folks here, ",
    "Get your boots on, ",
    "Quit actin' like a possum, ",
    "You ain't dead 'til I say so, ",
    "Move yer keister, ",
    "Don't be nappin' on my watch, ",
    "Time to git 'er done, ",
    "You best get back up, ",
    "Quit playin' dead, ",
    "Don't be draggin' your tail, ",
    "Shake the dust off, ",
    "Get yer head outta the clouds, ",
    "Ain't no time fer slackin', ",
    "Come on, y'all, git up, ",
    "Quit layin' on the ground like a sack o' spuds, ",
    "Don't be a lazy dog, ",
    "Better get movin' 'fore the sun sets, ",
    "Git up or git lost, ",
    "Rise up, y'all!"
}
mes2[9] =
{
    ", the hoedown ain't waitin'.",
    ", or the fish'll get away.",
    ", 'fore the truck's gone.",
    ", and the moonshine's runnin' low.",
    ", 'cause the deer's still out there.",
    ", and the tractor needs ya.",
    ", 'fore the cows wander off.",
    ", 'cause the barbecue's burnin'.",
    ", and the banjo's pickin'.",
    ", or the huntin' season closes.",
    ", and the whiskey's pourin'.",
    ", 'fore the hound gets restless.",
    ", and the porch swing's waitin'.",
    ", or the barbecue gets cold.",
    ", and the hootenanny's startin'.",
    ", 'fore the possum comes back.",
    ", and the creek's callin'.",
    ", 'cause the coon dogs are yappin'.",
    ", 'fore the moon's hidin' behind the clouds.",
    ", and the fishin' hole's open.",
    ", 'fore the fireflies go to bed.",
    ", and the moonshine's callin'.",
    ", or the jug band quits playin'.",
    ", 'cause the corn's ready to pick.",
    ", and the jug's runnin' dry.",
    ", 'fore the porch light goes out.",
    ", and the raccoons are gettin' bold.",
    ", or the barbecue's outta sauce.",
    ", and the dogs are barkin'.",
    ", 'fore the fire's gone cold.",
    ", and the hoedown's over."
}
mes1[10] = -- wall street style
{ 
    "Initiating portfolio resurrection for ",
    "Activating equity recovery protocol on ",
    "Deploying capital infusion for ",
    "Commencing market repositioning of ",
    "Triggering shareholder value restoration on ",
    "Executing asset reallocation for ",
    "Engaging liquidity boost on ",
    "Reinstating operational viability for ",
    "Launching corporate revival sequence on ",
    "Authorizing fiscal revitalization of ",
    "Commencing strategic turnaround for ",
    "Allocating capital reserves to ",
    "Engaging risk mitigation measures on ",
    "Initiating cash flow resuscitation for ",
    "Deploying human capital recovery on ",
    "Activating compliance realignment for ",
    "Executing stakeholder confidence rebuild on ",
    "Commencing synergy optimization for ",
    "Authorizing bottom-line enhancement on ",
    "Initiating brand reputation management for ",
    "Deploying market share recovery on ",
    "Engaging profit margin restoration for ",
    "Launching operational efficiency upgrade on ",
    "Activating competitive advantage strategy for ",
    "Executing growth trajectory reset on ",
    "Initiating fiscal health monitoring for ",
    "Deploying crisis management protocols on ",
    "Engaging enterprise value enhancement for ",
    "Authorizing revenue stream revitalization of ",
    "Commencing shareholder return optimization for "
}
mes2[10] =
{
    ". Please maintain KPI compliance.",
    ". Ensure adherence to quarterly targets.",
    ". Shareholder approval pending your response.",
    ". Synergy potential maximized upon revival.",
    ". Risk assessment recommends immediate action.",
    ". Please refrain from further operational failures.",
    ". Pending audit clearance for full reinstatement.",
    ". Compliance department monitoring performance metrics.",
    ". Boost shareholder confidence with timely recovery.",
    ". Anticipate increased market volatility post-revival.",
    ". Please align with corporate governance protocols.",
    ". Your operational downtime impacts ROI calculations.",
    ". Profitability projections recalibrated post-event.",
    ". Please submit post-mortem analysis report.",
    ". Resource allocation contingent on performance improvement.",
    ". Executive leadership awaiting your productivity increase.",
    ". Continue adhering to fiscal responsibility guidelines.",
    ". Return on investment expected to normalize shortly.",
    ". Strategic KPIs require immediate focus post-revival.",
    ". Fiscal year targets adjusted to accommodate downtime.",
    ". Efficiency metrics suggest room for rapid recovery.",
    ". Pending board review for performance revalidation.",
    ". Market analysts projecting cautious optimism.",
    ". Risk exposure elevated; mitigate accordingly.",
    ". Immediate action required to sustain growth trajectory.",
    ". Please engage cross-functional teams to optimize output.",
    ". Revenue growth forecast improved with your return.",
    ". Stakeholder engagement metrics rising post-resurrection.",
    ". Compliance checks scheduled following asset recovery.",
    ". Operational resilience scores updated post-mortem."
}
mes1[11] = --military briefing/intel report style
{
    "Target %t, status update: mission resumed. ",
    "Intel confirms %t has rejoined the front lines. ",
    "Subject %t extracted from downtime, ready for redeployment. ",
    "Recon reports %t back in action. ",
    "Unit %t operational and reporting for duty. ",
    "Command authorizes revival protocol on %t. ",
    "Field operative %t has re-engaged hostile territory. ",
    "Situation normal, %t is back online. ",
    "Revival confirmed, %t is combat-ready. ",
    "Tactical advantage regained with %t's return. ",
    "Trooper %t back on the battlefield. ",
    "Extraction successful; %t revived. ",
    "All units, %t has been reactivated. ",
    "Mission parameters updated: %t is alive. ",
    "%t is a live asset once more. ",
    "Squad update: %t has re-entered the fray. ",
    "Unit %t restored to operational status. ",
    "Command clearance granted for %t's return. ",
    "Revival protocol executed flawlessly on %t. ",
    "Combatant %t resupplied and revived. ",
    "%t rejoined squad, ready for objectives. ",
    "Intel indicates %t is back in play. ",
    "Recon unit %t has been resurrected. ",
    "All clear: %t is mission-capable. ",
    "Asset %t reinstated with full combat support. ",
    "Operational readiness confirmed for %t. ",
    "Tactical recovery of %t completed. ",
    "Target %t secured and back in action. ",
    "Revival success confirmed; %t is green to go. ",
    "Unit %t standing by for further orders. "
}

mes2[11] =
{
    ", maintain radio silence until extraction.",
    ", proceed with caution under heavy fire.",
    ", enemies still active in the AO.",
    ", secure all objectives before engaging.",
    ", mission priority updated; stay alert.",
    ", intel suggests hostile activity nearby.",
    ", report all contact with enemy forces.",
    ", await further command before advancing.",
    ", maintain formation and cover fire.",
    ", watch your six; threat level elevated.",
    ", ensure tactical advantage at all times.",
    ", casualties expected; move swiftly.",
    ", coordinates confirmed; move to rendezvous point.",
    ", recon team reports increased enemy presence.",
    ", follow protocol for extraction under fire.",
    ", maintain comms and report status regularly.",
    ", keep your weapon ready at all times.",
    ", expect enemy reinforcements shortly.",
    ", reinforce defensive positions immediately.",
    ", move out in teams of two.",
    ", stay low and avoid unnecessary exposure.",
    ", resupply points located ahead.",
    ", maintain perimeter security.",
    ", report any unusual activity ASAP.",
    ", operational risk remains high.",
    ", proceed with stealth and precision.",
    ", target elimination priority one.",
    ", coordinate with air support if needed.",
    ", hold position until further instructions.",
    ", adapt to battlefield conditions quickly."
}
mes1[12] = --angry karen style
{
    "Excuse me, but ",
    "Honestly, ",
    "Can someone explain why ",
    "I demand to know why ",
    "This is unacceptable, ",
    "Seriously, ",
    "Do you realize that ",
    "I can't believe ",
    "If this happens again, ",
    "I'm calling the manager because ",
    "Let me just say, ",
    "For the last time, ",
    "Is anyone paying attention to ",
    "How dare you let ",
    "I'm filing a complaint because ",
    "Unbelievable! ",
    "You better fix this because ",
    "Listen here, ",
    "I want answers about ",
    "This is ridiculous, ",
    "I'm not happy with ",
    "Who's responsible for ",
    "Let me make this clear, ",
    "No more excuses for ",
    "I've had enough of ",
    "You better start caring about ",
    "Get your act together, ",
    "Enough is enough with ",
    "You owe me an explanation for ",
    "I'm not leaving until ",
     "Well, let me tell you, ",
    "Heads are gonna roll because ",
    "If you think I'm calm, wait until you hear why ",
    "Brace yourself, because ",
    "I've never been so offended by ",
    "You're testing my limits with ",
    "I want to speak to whoever let ",
    "This is the definition of failure: ",
    "It's 2025 and yet ",
    "I can't even with ",
    "This is not how you do business: ",
    "Don't even try to explain ",
    "You better make it right, because ",
    "I'm already on the phone with HR about ",
    "I've got a full list of complaints starting with ",
    "Tell me why ",
    "You're seriously risking it all with ",
    "I need a manager, ASAP, because ",
    "You've ruined my day thanks to ",
    "Someone's about to lose their job over ",
    "Let me clarify how unacceptable ",
    "I don't care what you say, ",
    "You're about to regret letting ",
    "I'm officially disgusted by ",
    "This is why the world's going downhill: ",
    "I demand immediate action for ",
    "I've never wanted to scream more than because of ",
    "Don't make me get my lawyer over ",
    "I'm writing a strongly worded letter about ",
    "If this happens again, I'm organizing a boycott of "
}
mes2[12] =
{
    ", my standards have been violated!",
    ", I'm not paying for this nonsense.",
    ", and this mess better be fixed immediately!",
    ", you clearly don't know what you're doing.",
    ", my patience has officially run out!",
    ", you need to step up your game now.",
    ", and this is why I'm never coming back.",
    ", that's the last straw for me.",
    ", do you even understand basic service?",
    ", my time is valuable, you know!",
    ", and I expect a full refund.",
    ", this is how you lose customers.",
    ", and I demand an apology.",
    ", what kind of operation is this?",
    ", I'm taking this to corporate!",
    ", you can bet I'm posting about this online.",
    ", because your incompetence is astounding.",
    ", and I'm not impressed one bit.",
    ", how do you sleep at night letting this happen?",
    ", and I expect better treatment next time.",
    ", my neighbors need to hear about this.",
    ", and I'm warning everyone I know.",
    ", because nobody else will put up with this.",
    ", and this is the worst experience ever!",
    ", I'm done with this nonsense.",
    ", and you should be ashamed!",
    ", I'm counting on you to make this right.",
    ", because I'm not going to let this slide.",
    ", and this service is utterly disgraceful.",
    ", until you fix this properly!",
    ", and nobody is safe from my wrath!",
    ", and I'm preparing a social media storm.",
    ", and I refuse to stay silent any longer.",
    ", and you'll regret it for weeks.",
    ", and that's just plain rude.",
    ", and my standards are clearly too high for you.",
    ", and it's unacceptable to let that slide.",
    ", and I'm keeping a detailed record.",
    ", and even my cat is disappointed.",
    ", and that's a personal attack.",
    ", and it's a disgrace to this establishment.",
    ", and I'm demanding your immediate resignation.",
    ", and I'm expecting a full refund and an apology.",
    ", and I'm going to make sure everyone knows.",
    ", and this is a public relations nightmare.",
    ", and I'm beyond livid right now.",
    ", and you better fix that immediately.",
    ", and I'm expecting some serious compensation.",
    ", and I will not be ignored.",
    ", and I'm assembling a petition as we speak.",
    ", and you're testing my patience to the max.",
    ", and I'm on a mission to expose this failure.",
    ", and this is a catastrophic breach of trust.",
    ", and I demand satisfaction.",
    ", and you're on thin ice.",
    ", and I'm telling everyone I know.",
    ", and this is grounds for immediate corrective measures.",
    ", and I won't hesitate to escalate.",
    ", and you better hope I'm joking.",
    ", and I'm making a scene as we speak."
}
mes1[13]= --I pretend that it's not my fault that you died style
{
  "Look, I didn't *see* you pull aggro, ",
  "Lag hit me too, bro, ",
  "If the healer didn't die first, I swear I would've helped, ",
  "Pretty sure your gear is broken, ",
  "It wasn't my job to save you, ",
  "I thought you were invincible, ",
  "Told you not to go in alone, ",
  "My UI bugged out, I swear, ",
  "I was distracted by my cat, ",
  "You looked fine last time I checked, ",
  "You didn't call for help loud enough, ",
  "Technically, I didn't *see* you die, ",
  "We all make choices, ",
  "It was a tactical death, ",
  "I was testing your survivability, ",
  "That's on the tank, not me, ",
  "You rushed in too fast, ",
  "You didn't dodge the AoE, ",
  "I blinked and you were dead, ",
  "My hands were full of loot, ",
  "I was mid-macro, ",
  "I thought feign death was real this time, ",
  "You didn't say the magic word, ",
  "In my defense, I was busy typing, ",
  "I was roleplaying a pacifist, ",
  "You were doing so well until you weren't, ",
  "I'm just a DPS, not a miracle worker, ",
  "Death is just another cooldown, ",
  "I was alt-tabbed for *just* a second, ",
  "Don't worry, I clipped the death for content, "
}
mes2[13]=
{
  ", and that's totally a skill issue.",
  ", but let's blame the tank instead.",
  ", so technically, that's a team wipe, not my fault.",
  ", but I support you emotionally.",
  ", and you died like a true hero… or something.",
  ", so I'll just say it was lag.",
  ", but hey, at least it was funny.",
  ", so let's just say it was a learning moment.",
  ", and your sacrifice will not be remembered.",
  ", but don't worry, I'll revive you eventually.",
  ", and I have zero regrets.",
  ", so let's agree to blame the healer.",
  ", and next time, don't stand in fire.",
  ", and that's what we call 'natural selection'.",
  ", so now you get to take a break, you're welcome.",
  ", so I hope you learned something.",
  ", and yet here we are again.",
  ", but you went down swinging, kind of.",
  ", and next time, just try not dying.",
  ", so now we both learned something: you squish easy.",
  ", and we all saw it coming… except you.",
  ", and you totally made that mob angry on purpose.",
  ", but the real loot was the lesson we learned.",
  ", so don't hate the player, hate the RNG.",
  ", but you're back now, stronger-ish.",
  ", so let's just pretend it never happened.",
  ", so technically, that was part of the strategy.",
  ", and I'll add that to the 'not my fault' list.",
  ", but I did try to warn you with vibes.",
  ", and I feel absolutely no guilt.",
}
mes1[14]= --overly dramatic, guilt-ridden healer who just couldn't save them in time
{
  "No... no, not again... I tried everything to save ",
  "Forgive me, I wasn't strong enough to protect ",
  "The gods have forsaken me, and now so has ",
  "My hands... they trembled when I reached for ",
  "I saw the light leave the eyes of ",
  "I will carry this failure for eternity, dear ",
  "Even the spirits wept when we lost ",
  "I screamed your name, but death had already claimed ",
  "Why must fate be so cruel to ",
  "I would trade my soul to bring back ",
  "In the chaos, I lost sight of ",
  "It was one second too late... I failed ",
  "I failed my duty... and I failed ",
  "If only I had one more moment with ",
  "Oh, mercy! Take me instead of ",
  "My spells faltered when they mattered most to ",
  "I beg the stars to undo what happened to ",
  "It haunts me, the silence that followed the fall of ",
  "Your sacrifice was not meant to be, ",
  "All the training... and I still couldn't save ",
  "This is the burden I must bear for losing ",
  "Please... wake up... I didn't mean to lose ",
  "I should have seen the danger before it took ",
  "No power can undo the pain of losing ",
  "Even time itself seemed to freeze as I failed ",
  "They told me healers had to be strong... they never mentioned losing ",
  "What healer am I, if I couldn't save ",
  "I reached out, but shadows swallowed ",
  "Even the Light looked away as we lost ",
  "In the pages of failure, your name, dear "
}
mes2[14]=
{
  ", and now the world feels colder.",
  ", and I can still hear your echo in the wind.",
  ", may your soul find the peace I couldn't give.",
  ", and no spell can mend my heart.",
  ", please haunt me—I deserve it.",
  ", and this guilt will never leave me.",
  ", I swear I'll never let it happen again.",
  ", I see you every time I close my eyes.",
  ", your death is etched into my being.",
  ", and now all my mana feels wasted.",
  ", my healing was just too weak.",
  ", I hope you can forgive me from beyond.",
  ", the party won't feel whole again.",
  ", I should've known you were too brave.",
  ", even my cooldowns mourn with me.",
  ", my fingers slipped, and you slipped away.",
  ", my soul aches with every step now.",
  ", and the shadows mock my failure.",
  ", no rez can fix what's broken in me.",
  ", the raid leader is going to be *so mad*.",
  ", and honestly, I think I need a sabbatical.",
  ", my heart can't crit heal this pain.",
  ", and I blame the lag... but I know the truth.",
  ", the logs will show I tried... but not enough.",
  ", and now the group chat is gonna be awkward.",
  ", I can't believe this is happening *again*.",
  ", I swear I clicked the right target!",
  ", why do they always die when I blink?",
  ", and I need a moment... or ten.",
}
mes1[15]= --"I failed to heal you and I'm totally heartbroken" theme — but now with a dramatic, overly emotional Japanese anime style
{
  "Yamete...! I wasn't fast enough to save ",
  "Iieeeee!! I couldn't protect ",
  "My healing... it wasn't enough for ",
  "I tried... I really did... but I couldn't reach ",
  "Forgive me, senpai... I failed ",
  "Why did it have to be you, ",
  "No... please... not ",
  "All my training... all those hours... and I lost ",
  "The light in your eyes... I couldn't keep it for ",
  "Nani!? How did I let this happen to ",
  "I swore on my blade to protect ",
  "The spirits entrusted me... and I failed ",
  "Please, Kami-sama, bring back ",
  "I shouted your name... but you didn't turn around, ",
  "I reached out through the smoke, but couldn't grab ",
  "Kuso!! I should've dodged for ",
  "Don't leave me alone, ",
  "You trusted me... and I let down ",
  "Even my ultimate couldn't save ",
  "I thought I was strong... until I lost ",
  "This pain... it's the price for failing ",
  "Even now, I hear your laughter echoing, ",
  "I was supposed to protect everyone... especially ",
  "I poured my soul into the spell... but I still lost ",
  "I begged the universe, but it didn't spare ",
  "No barrier, no potion could protect ",
  "I feel so powerless... I couldn't even shield ",
  "Please don't close your eyes, ",
  "Why did you have to smile like that, ",
  "I told you I'd always be there for ",
}
mes2[15]=
{
  ", and now the sakura fall in silence.",
  ", and my heart will never mend.",
  ", please… come back and scold me again.",
  ", your warmth still lingers on my hands.",
  ", and I'll carry this pain to the next life.",
  ", even the wind mourns your loss.",
  ", I'll keep fighting… for your dream.",
  ", and now the stars feel further away.",
  ", your name will echo through every battle I fight.",
  ", I failed as your healer… and as your friend.",
  ", may the cherry blossoms guide your soul.",
  ", and now I walk this path alone.",
  ", and I will never forgive myself.",
  ", your voice… it's gone from our world.",
  ", I'll never laugh that way again.",
  ", I swore to protect everyone… and still lost you.",
  ", and my tears won't stop falling.",
  ", I'll offer my next victory to your memory.",
  ", I'll scream your name until the gods hear me.",
  ", and I'll wear your memory like armor.",
  ", and I failed you in the worst way.",
  ", even my ultimate couldn't rewrite this fate.",
  ", I wasn't strong enough to rewrite your destiny.",
  ", why… why wasn't it me instead?",
  ", you were my light... now I wander in shadow.",
  ", your smile… it's burned into my soul.",
  ", I don't deserve to wear this healer robe anymore.",
  ", the final episode wasn't supposed to end like this.",
  ", I hope the afterlife has better healers.",
}
mes1[16]= --“I failed to heal you and I'm totally heartbroken” concept — but now in the style of a '90s American action blockbuster
{
  "They took you down before I could patch you up, ",
  "I was reloading while they got to ",
  "I blinked once, and lost ",
  "My medkit was empty when you needed it, ",
  "I should've cleared the damn area first for ",
  "They came in hot, I couldn't cover ",
  "I told you to wait for backup, ",
  "I was five seconds too late for ",
  "I tried to drag you out of the blast zone, ",
  "I gave the signal, but no one reached ",
  "I lost good people today... including ",
  "They said it was a suicide mission. I didn't think it'd be ",
  "I've patched up worse, but I couldn't fix ",
  "I had one job — keep you alive, ",
  "You trusted me with your six, and I failed ",
  "The bullets stopped, but the silence after losing ",
  "I've seen a lot, but nothing hits like losing ",
  "I was too busy shooting to notice what happened to ",
  "You told me not to let you die, ",
  "I yelled 'Stay with me!' — but it didn't reach ",
  "The blast threw me back... and you were gone, ",
  "I couldn't pull you out in time, ",
  "You went in guns blazing — I should've covered ",
  "We made it through worse… but not this time, ",
  "You took the hit meant for me, ",
  "I held the med injector, but I couldn't reach ",
  "I saw it coming, but couldn't stop it from hitting ",
  "I froze for one second... and that was enough for ",
  "You saved the mission... but I couldn't save ",
  "I thought I was invincible... until I lost "
}
mes2[16]=
{
  ", and that's on me — all of it.",
  ", and I'm gonna carry that till my last breath.",
  ", and now there's one less dog tag in the squad.",
  ", I failed you, and I won't forgive myself.",
  ", and the war just got personal.",
  ", I owe you a hundred lifetimes of payback.",
  ", and I'll make sure they remember your name.",
  ", you went down like a hero.",
  ", and they'll wish they never crossed us.",
  ", now it's revenge time.",
  ", and I'm not leaving another man behind again.",
  ", this mission's for you now.",
  ", I'll bury them with lead and guilt.",
  ", but your fight isn't over — it's mine now.",
  ", and I'm still hearing the comms go silent.",
  ", and you were the best damn fighter I knew.",
  ", I'll torch the whole damn zone in your honor.",
  ", and I'm coming for payback.",
  ", and this time, I won't hesitate.",
  ", they'll pay in bullets and blood.",
  ", I lost a brother… no, a legend.",
  ", and now I fight with nothing to lose.",
  ", I'll keep the dog tags. And the rage.",
  ", it was supposed to be me, not you.",
  ", I should've taken the hit.",
  ", and I swear I'll end this war myself.",
  ", and the battlefield just got a whole lot colder.",
  ", we trained for this... but we never trained for losing you.",
  ", now it's personal. Real personal.",
  ", they thought they won — but I'm still standing.",
}
mes1[17]= --“I failed to heal you and I'm totally heartbroken”, but now with dust, drawls, and dramatic stares across the prairie.
{
  "I saw the bullet comin', but my hands were too slow for ",
  "You rode into that ambush, and I was still saddlin' up for ",
  "The vultures circled before I even got to ",
  "My whiskey flask was full, but my med bag was empty for ",
  "You bled out while I cursed the rattler trailin' ",
  "I hollered your name, but the wind took it from ",
  "I reached out, but them coyotes got to ",
  "You drew first, but I shoulda drawn faster for ",
  "The dust hadn't even settled when I lost ",
  "I saw your shadow fall in the moonlight, ",
  "Your boots were still smokin' when I found ",
  "I was fixin' the fence when the devil came for ",
  "They say every outlaw meets their match... I just didn't think it'd be ",
  "You told me you'd be fine — damn fool I was to believe ",
  "I stayed back when I shoulda ridden with ",
  "I left for jerky, came back missin' ",
  "You were tougher than a two-dollar steak, but not tough enough, ",
  "Your hat's still hangin' on the post, ",
  "The prairie's quieter without ",
  "You trusted me to watch your back, and I let down ",
  "You died under the same stars we rode beneath, ",
  "You ain't even finished your beans, ",
  "The fire's burnin' low, just like the hope I had for ",
  "I packed one too few bandages for ",
  "You always laughed at death — till it got the last word with ",
  "You left your harmonica behind, ",
  "Them buzzards won't find nothin' left of ",
  "You wanted to go out with guns blazin' — but I couldn't load in time for ",
  "The town still whispers about ",
  "I reckon I lost more than a partner when I lost ",
}
mes2[17]=
{
  ", and that guilt's gonna ride with me ‘til the end of the trail.",
  ", and I swear I'll never touch a deck of cards again.",
  ", and I ain't slept a wink since.",
  ", and now your horse just waits by the gate, silent as a grave.",
  ", and I reckon no saloon's loud enough to drown it out.",
  ", and I'll be seein' your ghost at every campfire.",
  ", and I'll spit at the sun ‘til it brings you back.",
  ", and the whiskey don't burn near as bad as that loss.",
  ", and your boots still got dust on ‘em.",
  ", and not even a six-shooter could shoot this pain away.",
  ", and now I talk to shadows like they'll answer back.",
  ", and I'd give my last bullet to take it back.",
  ", and it weren't even a fair fight.",
  ", and this town got real quiet since.",
  ", and I still hear the echo of your laugh ‘round the canyon.",
  ", and even the coyotes ain't howlin' tonight.",
  ", and I keep expectin' to see you ridin' over that hill.",
  ", and now the wind only brings back memories.",
  ", and the poker table feels emptier than ever.",
  ", and not a soul's stepped in your boots since.",
  ", and now I wear your hat like a crown of shame.",
  ", and I'll bury that regret deeper than any gold.",
  ", and the fire's gone out in more ways than one.",
  ", and no bounty will ever make it right.",
  ", and I'll carry that wound longer than my scars.",
  ", and the saloon girls still ask where you went.",
  ", and I told the preacher he could save his prayers.",
  ", and I left your rifle on the hill, where you last stood.",
  ", and you left me with more ghosts than bullets.",
  ", and I ain't never drawin' again unless it's in your honor.",
}
mes1[18]= -- The ultra-cheery hype for mes1 paired with a chilling, horror-themed mes2
{
    "You did amazing, ",
    "Keep shining bright, ",
    "Absolutely unstoppable, ",
    "The raid's lucky to have you, ",
    "Legend in the making, ",
    "Your spirit is unbreakable, ",
    "Rise like a champion, ",
    "Nothing can keep you down, ",
    "Unstoppable force detected: ",
    "You make the impossible possible, ",
    "A true hero returns, ",
    "The fight is yours to win, ",
    "Your comeback is inspiring, ",
    "We believe in you, ",
    "A shining star rises again, ",
    "Your resilience is unmatched, ",
    "Keep showing them how it's done, ",
    "The raid counts on your brilliance, ",
    "You're the heart of the team, ",
    "Back stronger than ever, ",
    "Every fall makes you stronger, ",
    "You dazzle us all, ",
    "Champion of the ages, ",
    "Your energy fuels the raid, ",
    "Power restored: ",
    "The comeback kid is back, ",
    "Unbreakable and untouchable, ",
    "Your legend just got bigger, ",
    "Keep the victory in sight, ",
    "Onward to glory, "
}
mes2[18]=
{
    ", but the shadows whisper your doom.",
    ", though death's grip still lingers.",
    ", while the void watches patiently.",
    ", but the nightmare never ends.",
    ", as the darkness breathes behind you.",
    ", though the curse clings tightly.",
    ", while ghosts lament your return.",
    ", but the cold silence follows close.",
    ", as the abyss stares into your soul.",
    ", though the shadows hunger for more.",
    ", but the grave has not forgotten.",
    ", as whispers creep through the dark.",
    ", though your fate may be sealed.",
    ", while the night watches you carefully.",
    ", but death's eyes never close.",
    ", as cold hands reach from below.",
    ", though the phantom waits patiently.",
    ", while darkness stirs with your breath.",
    ", but the curse is far from lifted.",
    ", as the eternal night holds its breath.",
    ", though the shadows claw unseen.",
    ", while the graveyard winds moan softly.",
    ", but the haunted past never fades.",
    ", as cold whispers call your name.",
    ", though the specter looms nearby.",
    ", while the darkness coils quietly.",
    ", but the ghostly veil has not lifted.",
    ", as the cursed night holds sway.",
    ", though the shadows dance behind you.",
    ", while death waits silently still."
}

message_types=tableLength(mes1); --a number of the message types (it should be equal for mes1 and mes2)

local _, class = UnitClass("player")
local rezSpell; --a variable for the resurrection spell name, that depends on the UnitClass
if class=="SHAMAN" then rezSpell="Ancestral Spirit";
elseif class=="PRIEST" then rezSpell="Resurrection";
elseif class=="PALADIN" then rezSpell="Redemption";
elseif class=="DRUID" then rezSpell="Rebirth";
end

SlashCmdList["REVIVEMACRO"] = function()
  CastSpellByName(rezSpell); --first cast the resurrection spell, cause sometimes you can't click a corpse directly (if the soul is released)
  message_type=random(message_types); --choose a random message type
  local r_mes1=random(tableLength(mes1[message_type])); --choose a random line from the chosen message type
  local r_mes2=random(tableLength(mes2[message_type]));
  full_message=mes1[message_type][r_mes1].."%t"..mes2[message_type][r_mes2]; --full message
  if UnitIsDead("target") then c="say" SendChatMessage(full_message, c, nil, UnitName("player")); -- if the target is dead, then write the message
end
end